export const Clubs = {
    "Augment AI":"augment",
    "Bullz Racing BMSCE":"bullz",
    "Central": "central",
    "Team Codelocked":"codelocked",
    "CIIE - Centre for Innovation Incubation and Entrepreneurship":"ciie",
    "ELSOC":"elsoc",
    "Entrepreneurship development Cell":"edc",
    "BMSCE IEEE Student Branch":"ieeesb",
    "BMSCE IEEE Computer Society":"ieeecs",
    "BMSCE IEEE PELS":"ieeepels",
    "BMSCE IEEE WIE":"ieeewie",
    "Fine Arts Club":"fac",
    "Institution's Innovation Council":"iic",
    "BMSCE IEEE PES and Sensors Council":"ieeepes",
    "Inksanity":"inksanity",
    "Respawn": "respawn",
    "Pentagram": "pentagram",
    "BMSCE Quiz Club":"quiz",
    "Google Developers Student Club":"gdsc" ,
    "Robotics club":"robotics",
    "Surya Energy Swaraj":"suryaes",
    "Singularity": "singularity",
    "Upagraha - The satellite club":"upagraha",
    "Aerospace Engineering":"aero",
    "Artificial Intelligence & Machine Learning":"aiml" ,
    "Biotechnology":"bio" ,
    "Chemical Engineering":"chem" ,
    "Civil Engineering":"civ" ,
    "Computer Science & Engineering":"cse" ,
    "Electrical & Electronics Engineering":"eee" ,
    "Electronics & Communication Engineering":"ece" ,
    "Electronics & Instrumentation Engineering":"eie" ,
    "Electronics & Telecommunication Engineering":"ete" ,
    "Industrial Engineering & Management":"iem" ,
    "Information Science & Engineering":"ise" ,
    "Mechanical Engineering":"mech" ,
    "Medical Electronics":"meel" ,
    "MBA":"mba" ,
    "MCA":"mca" ,
    "Test":"test"	//test club for testing purposes
  }