import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Avatar, Button, Flex, Heading } from '@chakra-ui/react'
import LoggedIn from '@/components/Landing/LoggedIn'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const res = await fetch("http://localhost:5500/api/getEvents",{
      method: "POST",
      headers: {
          "Content-Type": "Application/json",
          "Authorization": "Bearer 346433c5cdf018029041"
      },
      body: JSON.stringify({email: "vineethh.is20@bmsce.ac.in"})
  });
  const data = await res.json()
  return {
      props: {
          data,
      }
  }
}


export default function Home({ data }: any) {

  return (
    <>
      <Head>
        <title>Utsav Coordinators portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {/* <Flex height="100vh" alignItems="center" justifyContent="center" direction="column">
              <Avatar size="2xl" name="utsav-logo" src="/images/utsav-logo.png" />
              <Heading mt="2rem">Coordinators Portal</Heading>
              <Button mt="2rem">Sign up with Google</Button>
          </Flex> */}
          <LoggedIn data={data} />
        </div>
      </main>
    </>
  )
}
