import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Avatar, Button, Flex, Heading } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Utsav Coordinators portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Flex height="100vh" alignItems="center" justifyContent="center" direction="column">
              <Avatar size="2xl" name="utsav-logo" src="/images/utsav-logo.png" />
              <Heading mt="2rem">Coordinators Portal</Heading>
              <Button mt="2rem">Sign up with Google</Button>
          </Flex>
        </div>
      </main>
    </>
  )
}
